all:
	arduino-cli compile -b arduino:mbed_nano:nano33ble -v --library \
	/home/alex/Documents/Arduino/libraries/STM32duino_VL53L4CX --build-path \
	./build .

compile:
	arduino-cli compile -b arduino:mbed_nano:nano33ble -v --library \
	/home/alex/Documents/Arduino/libraries/STM32duino_VL53L4CX --build-path \
	./build --only-compilation-database .
