cmake_minimum_required(VERSION 3.20.0)


find_package(Zephyr REQUIRED HINTS $ENV{ZEPHYR_BASE})
project(drone-fc)

target_sources(app PRIVATE src/main.c)
target_sources(app PRIVATE src/sparkfun_icm20948/ICM_20948_C.c)
target_sources(app PRIVATE src/vl53l4cx/vl53l4cx_all.c)
target_sources(app PRIVATE src/vl53l4cx/vl53l4cx_api.c)
target_sources(app PRIVATE src/vl53l4cx/vl53l4cx_api_calibration.c)
target_sources(app PRIVATE src/vl53l4cx/vl53l4cx_api_core.c)
target_sources(app PRIVATE src/vl53l4cx/vl53l4cx_api_debug.c)
target_sources(app PRIVATE src/vl53l4cx/vl53l4cx_api_preset_modes.c)
target_sources(app PRIVATE src/vl53l4cx/vl53l4cx_class.c)
target_sources(app PRIVATE src/vl53l4cx/vl53l4cx_core.c)
target_sources(app PRIVATE src/vl53l4cx/vl53l4cx_core_support.c)
target_sources(app PRIVATE src/vl53l4cx/vl53l4cx_dmax.c)
target_sources(app PRIVATE src/vl53l4cx/vl53l4cx_hist_algos_gen3.c)
target_sources(app PRIVATE src/vl53l4cx/vl53l4cx_hist_algos_gen4.c)
target_sources(app PRIVATE src/vl53l4cx/vl53l4cx_hist_char.c)
target_sources(app PRIVATE src/vl53l4cx/vl53l4cx_hist_core.c)
target_sources(app PRIVATE src/vl53l4cx/vl53l4cx_hist_funcs.c)
target_sources(app PRIVATE src/vl53l4cx/vl53l4cx_nvm.c)
target_sources(app PRIVATE src/vl53l4cx/vl53l4cx_platform_ipp.c)
target_sources(app PRIVATE src/vl53l4cx/vl53l4cx_register_funcs.c)
target_sources(app PRIVATE src/vl53l4cx/vl53l4cx_sigma_estimate.c)
target_sources(app PRIVATE src/vl53l4cx/vl53l4cx_silicon_core.c)
target_sources(app PRIVATE src/vl53l4cx/vl53l4cx_wait.c)
target_sources(app PRIVATE src/vl53l4cx/vl53l4cx_xtalk.c)
# zephyr_compile_options(-Wno-unused-variable -Wno-comment)
